# Generated by Django 4.1.6 on 2023-02-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=5)),
                ('rakah', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('rakah', models.CharField(max_length=50)),
                ('giblat', models.CharField(max_length=10)),
            ],
        ),
    ]
